### PR TITLE
Framework integration

### PR DESCRIPTION
**Pull request by paldepind**
**Not ready for merging**

Testing frameworks typically export a function called `test` or `it` for creating tests. This function has basically the same API in all frameworks. This PR uses that to create a function called `createProperty` (I'm not sure if that's a good name). It then returns a new function that arguments the `test` function and uses it to create tests based on ts-quickcheck.

Then property-based tests can be created very concisely.

```ts
// Pass Mochas `it` function to `createProperty`
const property = QC.createProperty(it);

describe("concat", () => {
  property(
    "left identity",
    QC.range(2)
      .array()
      .map(fromArray),
    xs => equals(concat(empty(), xs), xs)
  );
  // ...
);
```

The function returned by `createProperty` also has a `only` and a `skip` method. This again uses the fact that all framework put a `only` and a `skip` on their `test` function. This makes the `property` function integrate nicely into the host testing framework.

```ts
property.skip( // Skip this one, still has bugs :(
  "associativity"
  QC.range(2)
    .array()
    .replicate(3),
  (xyz) => { /* ... */ }
);
```

This should work with at least Mocha, AVA, Jest and Jasmine.

I have not written tests yet. I'd like to hear what you think @danr :smile:

### CODE REVIEW

**Comment by danr** [comment]
I'm all for this, it's essentially what the `adaptTape` code does:

https://github.com/danr/ts-quickcheck/blob/f09bd3c1252cd3df943055de8ccac1d70a1eb027/src/main.ts#L43-L49

A difference is that I've been using the `stdoutForall` version that writes on stdout instead of throwing an exception, but I think the version that throws an exception might work just as fine.

Another question is if it should wrap the version that returns a boolean or the one that fails by throwing exceptions (as you point out in #5.)

**Comment by paldepind** [comment]
> Another question is if it should wrap the version that returns a boolean or the one that fails by throwing exceptions (as you point out in #5.)

I think both would be useful. The boolean one can be very convenient with property tests and the throwing one will be more familiar to many people. But, I can't think of good consistent names.

| | Standalone check | Framework integrated |
| - | - | - |
| Expects test to return `boolean` | `assertForall` | `property` (created by `createProperty`) |
| Expects test to throw | ? | ? |

Another approach would be to combine the two things in one. If the predicate function returns `true` or `undefined` it's considered a success. If it returns `false` or throws it's considered a failure. The benefit is that then one function can be used in both cases. The downside is that if you return `undefined` by accident when you intended to return a `boolean` (for instance by forgetting `return`) then your tests will all pass without actually checking anything. So that approach is probably not so good.

**Comment by paldepind** [comment]
> A difference is that I've been using the `stdoutForall` version that writes on stdout instead of throwing an exception, but I think the version that throws an exception might work just as fine.

A least for Mocha throwing an exception will result in nicer output. After running all tests Mocha prints a summary at the end with all the failing tests and the error message they threw. Anything that gets printed during the test can easily get drowned by all the other output.

**Comment by danr** [comment]
I will sleep on this issue and probably do an alpha release tomorrow to make it easy to test this in other projects. Thanks a lot for all your input and encouragement this weekend @paldepind , it's been great :+1:

**Comment by paldepind** [comment]
I just realized that throwing inside the prop function has a huge advantage: One can get a descriptive error message about what went wrong since the assertion frameworks throw quite very nice error messages.

If the prop function returns `true` or `false` then when it fails you don't know anything about why. The user can see the counterexample but nothing more. When throwing a user can see both the counterexample _and_ a descriptive error message about what went wrong.

To me that is significant enough that I fell ts-typecheck should nudge users towards using assertions.

> Thanks a lot for all your input and encouragement this weekend @paldepind , it's been great 👍

It has been a pleasure 😄

**Comment by danr** [comment]
Hi, I merged your commit anyway :) I haven't added any integration tests with mocha, PRs welcome :)

> To me that is significant enough that I fell ts-typecheck should nudge users towards using assertions.

I think what would make sense then is to provide two versions of `createProperty`. The user probably prefers one style and will just instantiate their favorite framework with that preferred choice.

Here are some names to start improving: `createAssertionProperty` and `createBooleanProperty`.

> If the prop function returns true or false then when it fails you don't know anything about why. The user can see the counterexample but nothing more. When throwing a user can see both the counterexample and a descriptive error message about what went wrong.

The log function on the property object is meant to mitigate that, you get to see the contents of the log of the last failing test. But yes, it's quite manual so using the assert instruments makes sense.

**Comment by paldepind** [comment]
> I think what would make sense then is to provide two versions of `createProperty`. The user probably prefers one style and will just instantiate their favorite framework with that preferred choice.

Yes, that is a good idea. But then maybe the documentation should nudge people toward using `createAssertionProperty`.

Here is an example of what I mean. If I write my test like this:

```ts
property(
  "sum of array is greater than or equal to length",
  QC.int.array(),
  xs => assert.isAtLeast(xs.reduce((n, m) => n + m, 0), xs.length)
);
```

Then I will get the following output:

```
sum of array is greater than or equal to length:
  Error: Exception when evaluating after 2:
  AssertionError: expected 1 to be at least 2 <-- this line is nice to have
  Exception occured with this input:
  [1, 0]
```

The text `AssertionError: expected 1 to be at least 2` is what I'm talking about. I can only get that output because I'm using assertions. In this example just seeing the counterexample would have been plenty but in the real-world seeing exactly why the assertions fail can be a huge help.

>  Here are some names to start improving: `createAssertionProperty` and `createBooleanProperty`.

I think those are very good names!

**Pull request closed without merging**
